### ISSUE TITLE
DAMN ! worker 10 (pid: 18950) died, killed by signal 9 :( trying respawn ...

### ISSUE THREAD

**Issue by LuPan2015** [baifendian/Sirius#1]
Sirius启动后访问不了. uwsgi log如下：
```bash
Wed Jul 27 07:25:07 2016 - *** HARAKIRI ON WORKER 9 (pid: 18949, try: 1) ***
Wed Jul 27 07:25:07 2016 - HARAKIRI !!! worker 9 status !!!
Wed Jul 27 07:25:07 2016 - HARAKIRI [core 0] 10.12.4.126 - GET / since 1469604246
Wed Jul 27 07:25:07 2016 - HARAKIRI !!! end of worker 9 status !!!
DAMN ! worker 9 (pid: 18949) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 9 (new pid: 19013)
Wed Jul 27 07:26:07 2016 - *** HARAKIRI ON WORKER 10 (pid: 18950, try: 1) ***
Wed Jul 27 07:26:07 2016 - HARAKIRI !!! worker 10 status !!!
Wed Jul 27 07:26:07 2016 - HARAKIRI [core 0] 10.12.4.126 - GET / since 1469604306
Wed Jul 27 07:26:07 2016 - HARAKIRI !!! end of worker 10 status !!!
DAMN ! worker 10 (pid: 18950) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 10 (new pid: 19051)
```

**Comment by typhoonzero** [comment]
看下请求处理的地方是在哪里超时卡住了？

**Comment by LuPan2015** [comment]
通过log初步发现请求还没有进到views那里。目前只有uwsgi里面有日志.
`root@hlg3p64-lupan log]# ll
总用量 32
-rw-rw-rw- 1 root root     0 7月  27 10:07 error.log
-rw-rw-rw- 1 root root     0 7月  27 10:07 hdfs.log
-rw-rw-rw- 1 root root     0 7月  27 10:07 service.log
-rw-r----- 1 root root 28446 7月  27 15:55 uwsgi.log
-rw-rw-rw- 1 root root     6 7月  27 15:23 uwsgi.pid`

**Comment by typhoonzero** [comment]
走到地方log还没打吧。。。

**Comment by LuPan2015** [comment]
url转发到view里面的函数第1行打了日志但就是没打呢。所以我发现还没有到views那层。
比如：
url.py:
`#encoding=utf8
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import patterns,url,include
import settings
from django.contrib import admin
admin.autodiscover()
import views
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^v1/user_auth/', include('user_auth.urls')),
    url(r'^v1/hdfs/', include('hdfs.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    #url(r'^$',views.login),
    **_## url(r'^login$',views.login),_**
    url(r'^logout$',views.logout),
    url(r'^HDFS/.*$',views.index)
]

# 可浏览式登录API
urlpatterns += patterns('',
    url(r'^api-auth/',include('rest_framework.urls',namespace='rest_framework')),
)`
views.py
`def login(request):
    **_ac_logger.info("######################login#######")_**
    if request.method == "POST":
        res = {}
        username = "pan.lu"
        password = "pan.lu"
        user = authenticate(username=username, password=password)
   ......
`

**Comment by LuPan2015** [comment]
pstack uwsgi的进程信息如下
```bash
[root@hlg3p64-lupan log]# pstack 23262
#0  0x00007fd3bfbfff13 in __epoll_wait_nocancel () from /lib64/libc.so.6
#1  0x000000000045ba2a in event_queue_wait_multi ()
#2  0x00000000004900c6 in uwsgi_corerouter_loop ()
#3  0x00000000004640c9 in gateway_respawn ()
#4  0x000000000042fd0d in master_loop ()
#5  0x0000000000468a57 in uwsgi_run ()
#6  0x00007fd3bfb35d5d in __libc_start_main () from /lib64/libc.so.6
#7  0x000000000041d7a9 in _start ()
[root@hlg3p64-lupan log]#
```

**Comment by LuPan2015** [comment]
我想我应该找到答案了:
```bash
[root@hlg3p64-lupan ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-LogVol00
                       48G   46G     0 100% /
tmpfs                  16G   12K   16G   1% /dev/shm
/dev/vda1             243M   77M  154M  34% /boot
/dev/vdb              200G   25G  176G  13% /opt
```

**Comment by typhoonzero** [comment]
额。。。磁盘满了居然。。。

**Comment by LuPan2015** [comment]
yes!
