### ISSUE TITLE
login的REST API发送的是明文密码，非https会存在安全隐患

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#100]
login的REST API发送的是明文密码，非https会存在安全隐患

建议的修改方式：
* 登录API使用HTTPS
* 密码只传输MD5或SHA1

**Comment by LuPan2015** [comment]
密码要是传输的是MD5那就没法解开向ldap验证了。前端的加密后端必须能解开才行。

**Comment by sjx323** [comment]
已在3.64上配置做nginx转发以及ssl配置 
本地配置host 172.24.3.64  siriustest.baifendian.com
即可访问https://siriustest.baifendian.com/
