### ISSUE TITLE
openstack相关页面 表格组件的使用问题

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#101]
Sirius 项目中所有的DataTable组件，都需要满足一个原则，就是不出现自带的分页，而应该在tbody标签上添加滚动条以实现大量条目的显示

如：![image](https://cloud.githubusercontent.com/assets/8321444/18246714/01dbd75e-73a0-11e6-80db-63f670ad740e.png)

### 涉及的页面
* 云主机
    * 计算
        * 虚拟机
        * 镜像
        * 云类型
    * 存储
        * 云磁盘

**Comment by linuxwind** [comment]
不知道这种方式能否分段加载数据，vm数量多的时候，一次需要加载的数据比较多，可能会出现性能问题。

**Comment by typhoonzero** [comment]
滚动到底部的时候在加载一页并展示即可。

**Comment by linuxwind** [comment]
@lsglsf  按照这种方式展示吧。

**Comment by lsglsf** [comment]
好！
