### ISSUE TITLE
openstack相关页面 导航栏结构

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#102]
各位看下，当前openstack的目录结构是否合适，是否需要改进
@Yancey1989 @typhoonzero @lsglsf @LuPan2015 
当前是这样的：
![image](https://cloud.githubusercontent.com/assets/8321444/18246844/e87fdcf0-73a0-11e6-9520-0690b18f05d6.png)

**Comment by qqzxingchen** [comment]
当前是这样的：
![image](https://cloud.githubusercontent.com/assets/8321444/18246830/d2e2f71a-73a0-11e6-85a1-f35e610315c0.png)

**Comment by qqzxingchen** [comment]
对了，大家可以看下合并openstack相关代码之后的页面
http://172.24.3.64:10088/openstack/instances

**Comment by typhoonzero** [comment]
暂时不用调整
