### ISSUE TITLE
openstack相关页面 表格组件的排序问题

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#104]
openstack的表格组件上面都有排序的图标，但是点击下去没有任何反应，应该是没有实现排序的回调函数
（bfd-ui里的DataTable组件，如果点击了排序的图标，则会回调一个函数，而实际的排序功能是自己实现的）

**Comment by lsglsf** [comment]
暂时没做排序！就按照创建顺序显示的！

**Comment by qqzxingchen** [comment]
那么修改的时候就暂时把排序的给去掉（order设置为false），不然看到之后第一反应就是这是个bug……

**Comment by lsglsf** [comment]
好！
