### ISSUE TITLE
openstack相关页面 的页面交互

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#107]
考虑一下，openstack相关页面是否需要与UI沟通，并出一个设计稿

**Comment by LuPan2015** [comment]
测试环境: [SiriusTest]( 172.24.3.64:10088)

**Comment by typhoonzero** [comment]
感觉可以先不用麻烦UI，页面的配色用统一的方式，页面的布局都是使用统一的UI，原型设计已经有了。如果有部分细节需要和UI确认再说。

**Comment by LuPan2015** [comment]
这个issue可以关闭了么
