### ISSUE TITLE
openstack后台 url配置

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#111]
以 云主机-计算-虚拟机 子页面为例：
如果用户直接点击左侧的导航栏，则右侧的子页面可以正常显示
如果用户点击导航栏之后，按下F5刷新，将会提示找不到页面，如：
![image](https://cloud.githubusercontent.com/assets/8321444/18260964/73009b42-7425-11e6-91d5-36f24a045651.png)

原因已经找到，但是因为这块是 @lsglsf 负责的，所以交给你改比较合适
找到 Aries/Aries/urls.py 文件
在内容
```
    url(r'^CalcManage/.*$',views.index),
    url(r'^CodisCloud/.*$',views.index),
```
的下面添加一行
```
    url(r'^openstack/.*$',views.index),
```

**Comment by lsglsf** [comment]
收到！谢谢！
