### ISSUE TITLE
[讨论]openstack前端代码是否有必要使用react代替jquery

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#112]
文件中引入了 jquery.min.js 文件，使用的地方为：
![image](https://cloud.githubusercontent.com/assets/8321444/18261091/7ed7e474-7426-11e6-959f-c26f901237e7.png)

建议评估一下是否有必要引入 jquery，前端同事给的建议是尽量使用react原生的语法

**Comment by typhoonzero** [comment]
尽量在标题中能概括问题，这样在issue列表中就能看明白

**Comment by qqzxingchen** [comment]
好
