### ISSUE TITLE
调整页面布局，去掉每个页面的标题描述，只保留面包屑

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#114]
调整页面布局，去掉每个页面的标题描述，只保留面包屑，原有标题放到<html><title>中，节省空间，减少页面元素冗余

![c404e50f-c4a4-45a6-aed5-91f830f8dc47](https://cloud.githubusercontent.com/assets/13348433/18306060/b78f8870-751c-11e6-9e6f-a7e58ee8c4cd.png)

**Comment by qqzxingchen** [comment]
@sjx323 @LuPan2015 @lsglsf @hyndaniel 
我已经把NavigationInPage这个组件的HeadText给去掉了，这对页面的样式造成了一些影响。
你们checkout一下 这个分支：fix#114-del-navigationinpage-headtext
然后直接再这个分支上进行修改吧

**Comment by LuPan2015** [comment]
好的。收到。

**Comment by LuPan2015** [comment]
HDFS云没有影响: 
![image](https://cloud.githubusercontent.com/assets/10804128/18624365/be39993e-7e79-11e6-998e-586bf79fc62d.png)

**Comment by LuPan2015** [comment]
用户管理没有影响:
![image](https://cloud.githubusercontent.com/assets/10804128/18624404/0f9cbafe-7e7a-11e6-9304-51fc1cc2e196.png)

**Comment by lsglsf** [comment]
修改完！

**Comment by LuPan2015** [comment]
@lsglsf 可以发个截图。

**Comment by lsglsf** [comment]
![qq 20160920172035](https://cloud.githubusercontent.com/assets/16957887/18664771/a820c720-7f56-11e6-87db-e8fc52103ed1.png)

**Comment by LuPan2015** [comment]
@qqzxingchen  给导航栏统一加个 margin-bottom 吧。 挨得太近了

**Comment by qqzxingchen** [comment]
@sjx323 @LuPan2015 @lsglsf @hyndaniel 
由于该次改动牵扯较大，经陆攀建议，在NavigationInPage组件去掉HeadText之后，为其统一设定一个 height（或者设置一个margin-bottom），这样其它页面都不需要再做任何操作就可以平滑过渡。因此这里将大家所做的提交全部回滚

**Comment by LuPan2015** [comment]
![image](https://cloud.githubusercontent.com/assets/10804128/18739880/26ba6c3e-80d9-11e6-8da0-b190302d6eaf.png)
新的还有上面这个问题么？ 改完了最好上个截图呢
