### ISSUE TITLE
OpenStack页面 使用antd组件导致 云容器-使用说明 下面的两个页面样式混乱

### ISSUE THREAD

**Issue by hyndaniel** [baifendian/Sirius#117]
**正常样式**：

![image](https://cloud.githubusercontent.com/assets/18070336/18341059/c704f218-75da-11e6-8184-2f402e293f77.png)

**现在样式**：

![image](https://cloud.githubusercontent.com/assets/18070336/18341067/d11b680e-75da-11e6-8565-f6f24c147264.png)

因为antd引用了*normalize.css v4.1.1*这个css样式，导致全局样式被复写，  如下： 

![image](https://cloud.githubusercontent.com/assets/18070336/18341556/16195bb2-75dd-11e6-8658-46ef5efb933a.png)

当我把margin, padding去掉之后，看上去是样式是恢复了，实际上markdown文档的列表小黑点也不知道去哪里了。如下：

![image](https://cloud.githubusercontent.com/assets/18070336/18341442/96df9014-75dc-11e6-9956-70c92303d30c.png)

建议使用公司的组件库bfd-ui。

**Comment by qqzxingchen** [comment]
@lsglsf  实际上这个问题之前开发的过程中也出现过，因此我们已经 弃用antd这个组件；希望你们那边评估一下，是否可以使用公司的bfd-ui，防止以后出现类似的问题

**Comment by lsglsf** [comment]
我们代码里面引用比较多的antd！去掉估计需要不少的时间！能不能先用着！慢慢去替换！

**Comment by qqzxingchen** [comment]
我觉得可以专门开一个分支，然后花费几天时间将它修复掉。像是这类问题，尽早该会比较快一点吧
