### ISSUE TITLE
云服务 > HDFS云 > 我的文件 中文文件，点击删除，删除失败，页面中也删除了文件

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#126]
有中文文件名的文件，点击删除操作，提示删除失败（弹框颜色是绿色，这也是一个问题）。

虽然删除失败，不手动刷新页面，此文件已经从页面上去掉了。

手动刷新页面，或切换文件夹，文件又会展示出来

**Comment by LuPan2015** [comment]
中文且带空格的时候会出现这种情况。 已修复
