### ISSUE TITLE
云服务 > HDFS云 > 我的分享 删除按钮有歧义

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#127]
我的分享删除按钮有歧义，容易让人理解成删除文件，应该改成取消分享的按钮

**Comment by hyndaniel** [comment]
武哥，请问取消分享的按钮是什么样的。。。。
另外，将对话框内容改成 “**确认取消分享？**” 可以达到消除歧义的效果吗？
![image](https://cloud.githubusercontent.com/assets/18070336/18503181/02af03fa-7a8e-11e6-8245-14a94e1b7f60.png)
