### ISSUE TITLE
[部署] 迁移Sirius的 日志和启动pid文件路径

### ISSUE THREAD

**Issue by LuPan2015** [baifendian/Sirius#132]
将Sirius的日志和pid文件迁移到Sirius目录下面，并且采用相对路径的方式指定和获取日志文件的路径。
当前是统一放在 /tmp/sirius 目录下。这样不是很优雅。

**Comment by sjx323** [comment]
统一放到与package同一目录下的log文件夹下

**Comment by LuPan2015** [comment]
增加download 时的缓存路径。也是放在package下面即可。
