### ISSUE TITLE
[讨论] 概览页面内容

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#136]
概览页面，目前只展示了2个假图，要考虑展示全局的更全面的内容。比如：

存储服务的状态
云容器服务的状态
云主机服务的状态等。

**Comment by typhoonzero** [comment]
[讨论记录] 根据space来展示每个服务的用量

1. HDFS使用百分比
1. HDFS分享文件的个数
1. HDFS datanode健康状态(99/100)
1. Codis 集群总个数(10/11， 正常集群／总集群)
1. Codis 内存使用率50%
1. Pod个数(9/10)，rc(9/10), Service状态(9/10)
1. Node个数
1. 今日正在运行的任务
1. 今日执行成功的任务
1. 今日运行失败的任务
1. 今日总任务
1. 虚拟机(9/10)
1. 镜像个数
1. 云磁盘个数
1. 当前space成员个数

使用说明

**Comment by typhoonzero** [comment]
@lsglsf @zd1990 都看下这些数据展示在概览页面是否可行～

**Comment by lsglsf** [comment]
可以

**Comment by zd1990** [comment]
ceph的使用情况和健康状态要加上吗？openstack的总体使用情况也可以加上（比如cpu、内存使用情况）

**Comment by linuxwind** [comment]
ceph 可用的存储总量，已分配。健康状态属于监控，不建议放概览里面。

**Comment by LuPan2015** [comment]
@hyndaniel @lsglsf @zd1990 @sjx323 @qqzxingchen  你们各自把你们服务取数据的REST API开发出来。我来一起展示。(也就是你们实现你们负责服务的api)。
**_实现了就直接在下面回复_**。 例如
HDFS如下:
1.  HDFS 使用百分比

``` Bash
url  /v1/HDFS/getCapacity/?spaceName=hadoop
```

返回:

``` Json
{
  code : 200,
  data : {
               //percent : 50% //百分比指标
               used: 30,
               nonUsed: 70,
               unit: "G",
             }
}
```
1.  HDFS 分享文件个数 

``` Bash
url /v1/HDFS/getShare?spaceName=hadoop
```

返回：

``` Json
{
   code : 200,
   data : {
                number : 50  //分享个数指标
             }
}
```

**Comment by LuPan2015** [comment]
1.HDFS 概览API为:

``` Bash
url http://172.24.3.64:10086/v1/hdfs/overview/?spaceName=hadoop
```

结果:

``` Json
 {
    "code": 200,
    "data": {
        "hdfs_datanodes": {  //datanode健康状态
             lives:  0,  //正常
             dead: 0   //异常
         }, 
        "hdfs_disk_used":{  //使用百分比
             used: 30,
             nonUsed: 70,
             unit: "G"
        },
        "hdfs_shares": 4 //分享文件的个数
    }
}
```
1. 用户管理API为:

``` Bash
url v1/user_auth/overview/?spaceName=hadoop
```

结果:

``` Json
{
    "code": 200,
    "data": {
        "count": 8
    }
}
```

**Comment by hyndaniel** [comment]
8-11 bdms 任务相关api
URL如下：
```Bash
/k8s/api/v1/dashboard/taskinfo
```
返回：
```Json
{
  "msg": "",
  "code": 200,
  "data": {
    "today_running_task": 0  //今日正在运行的任务数
    "today_succeed_task": 666,  //今日运行成功的任务数
    "today_failed_task": 171,  //今日运行失败的任务数
    "today_total_task": 837,  //今日运行的总任务数
  }
}
```

**Comment by lsglsf** [comment]
openstack 概览API为
URL /openstack/home/overview/
返回：
{
    "code":200,
    "data":{
        "volume":9, //云磁盘个数
        "image": 3, //镜像个数
        "vm":"10/11" //虚拟机
    }
}

**Comment by abigbigbird** [comment]
codis 概览API为
URL /v1/codis/codisoverview/
返回：
{
"msg": "OK", 
"code": 200, 
"data": {
"nice_codis_count": 3, //正常codis集群个数
"all_codis_count": 4, //codis集群总个数
"memory_used_count": 360, //集群已分配内存
"memory_total_count": 30000 //集群总内存
}
}

**Comment by qqzxingchen** [comment]
Pod、rc、Service、Node信息：
```
url : k8s/api/v1/namespaces/(?P<namespace>\w{1,64})/pods  
type : GET
return:  
    {
        code : 
        msg : 
        data: {
            pod:  {   count : 9 , total : 10  },
            rc:  {   count : 9 , total : 10  },
            service:  {   count : 9 , total : 10  },
            node:  {   count : 9 , total : 10  }
        }
    }
```

**Comment by LuPan2015** [comment]
概览页面目前如下:
![image](https://cloud.githubusercontent.com/assets/10804128/18778276/31afc706-81a6-11e6-8ae6-fe0a45604f76.png)

**Comment by LuPan2015** [comment]
目前鲁谷版本只剩下openstack概览没有。由于release－0.3不上openstack故改issue推迟到v0.4版本彻底修复
![image](https://cloud.githubusercontent.com/assets/10804128/18938675/fcdaad12-862c-11e6-8545-c9480226e80e.png)
