### ISSUE TITLE
[全局] 将settings.py中需要更改的配置部分提取到xml文件中

### ISSUE THREAD

**Issue by LuPan2015** [baifendian/Sirius#143]
如题: 
建议将settings.py文件中依赖具体环境的配置文件提取到xml文件中。这样每次部署环境时只需要修改xml文件即可。而不用修改python文件。
比如一下是需要修改的配置:

1. k8s 服务地址信息
2. hdfs 服务地址信息
3. bdms 服务地址信息
4. ldap 服务地址信息
5. 数据库配置信息
6. codis设置信息等

**Comment by typhoonzero** [comment]
不要用xml把，写起来那么麻烦，用yaml或者json。yaml写起来最简单

**Comment by LuPan2015** [comment]
嗯。直接用json也行。
json的格式是不是的这样?
```Json
{ key:value, #后面加上基本的描述？
}
```

**Comment by LuPan2015** [comment]
目前部署使用的配置就是更改后的配置。没有问题
