### ISSUE TITLE
opensatck虚拟机监控流程

### ISSUE THREAD

**Issue by zd1990** [baifendian/Sirius#156]
### 监控流程
openstack的监控现在是放在monitor的项目里面作为一个监控的子模块。

- 数据采集: 
    通过libvirt提供的接口遍历获取单台计算节点上的所有虚拟机的cpu、磁盘、网卡、内存的相关信息。在有多台计算节点的情况下，将所有计算节点单台获取信息的任务丢入线程池中循环做，默认开启3个线程。

- 数据处理：
  由于通过libvirt获取的数据都是总的信息，比如磁盘获取的信息为read_bytes、read_requests、write_bytes、write_requests，都是磁盘从开机到现在总的读写量和读写次数，如果需要获取磁盘当前的mbps和iops需要sleep1秒再获取一次数据相减。测试监控30-40台虚拟机，获取一次最终数据的时间（减去sleep的1秒）大概花了0.4秒左右。

- 数据存储：
原先设计用mysql存储数据，表的结构为：
instance_cpu_datetime    cpu相关信息(util),datetime为当前年份和月份，比如201609，作为分表依据
instance_disk_datetime   磁盘相关信息(rops、rbps、wops、wbps)
instance_nic_datetime   网卡相关信息(tx_byte、tx_packets、rx_byte、rx_packets)
instance_mem_datetime  内存相关信息(free、used、total、util)
instance   虚拟机信息(uuid、hostname、所在的物理机)
disk_info  磁盘物理信息(盘符名、所在的虚拟机),通过唯一id和instance_disk_datetime表关联
cpu_info  cpu物理信息(cpu核数、所在的虚拟机),通过唯一id和instance_cpu_datetime表关联
nic_info   网卡物理信息(网卡名、mac地址、所在的虚拟机),通过唯一id和instance_nic_datetime表关联
还有相关的存储过程和查询视图

### 数据存储的问题
大致计算了下，在有100台虚拟机的情况下，30秒采集一次数据，每天每张表的数据量在30W-100W，后面监控页面查询数据时不知道有多大的延时。
opentsdb数据库没有接触过，不知道单表有大量数据时性能怎么样。

**Comment by typhoonzero** [comment]
TSDB是专门为存储时间序列数据而设计，尤其适用于存储监控数据，而且可以使用grafana直接配置监控图表。TSDB后是使用HBase作为存储引擎，查询效率调优之后能在大量监控数据中快速查询。平台通用的监控，都需要统一将数据接入TSDB

**Comment by linuxwind** [comment]
武哥，提供一个可以测试的opentsdb，测试一下。
