### ISSUE TITLE
bfd-ui升级表单验证影响问题

### ISSUE THREAD

**Issue by LuPan2015** [baifendian/Sirius#180]

**Comment by LuPan2015** [comment]
初步计划是先和江海确认组件升级的影响。然后单独回滚bfd-ui的部分组件。后期修改成兼容bfd-ui最新版本。

**Comment by qqzxingchen** [comment]
页面url ： /CloudHost/Calculation/Instances
点击“创建”按钮

**Comment by qqzxingchen** [comment]
@lsglsf 如果问题已经解决，请在pr合并到dev分支之后关掉这个issue

**Comment by lsglsf** [comment]
好的！
