### ISSUE TITLE
openstack相关模块的django后台部分代码需要重写

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#186]
1. 使用统一的django数据库
2. 使用统一的日志配置
3. 在view中的访问数据库的操作统一使用model，不出现sql操作

https://github.com/baifendian/Sirius/pull/184 这个PR先关闭掉，需要新启动一个PR来修复此问题

**Comment by LuPan2015** [comment]
好的。先关闭 。 #184  , #170  这两个pr.
