### ISSUE TITLE
修改docker镜像系统中的hosts

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#219]
当前 influxdb 数据库已经可用，k8s监控概览页面已经可以查看到数据，但是由于influxdb的地址发生了变化，需要重新配置一下 hosts

```
# vim /etc/hosts ，在文件尾添加一行：
117.121.9.156   k8sinfluxapi.bfdcloud.com
```

**Comment by linuxwind** [comment]
这个为啥用influxdb？不是采集到的监控数据都放入opentsdb吗？

**Comment by qqzxingchen** [comment]
当前线上的解决方案是 k8s + influxdb + grafana。k8s监控概览页面显示的内容与grafana的显示内容很相似，因此就直接使用了influxdb

**Comment by LuPan2015** [comment]
貌似好像不用配置了。
