### ISSUE TITLE
云硬盘 未选中情况下，隐藏 更多操作

### ISSUE THREAD

**Issue by linuxwind** [baifendian/Sirius#240]

**Comment by qqzxingchen** [comment]
我可否理解为：
当列表坐车未选中任何记录时，“更多操作”按钮隐藏或者置灰（我觉得置灰会比较好点），且不响应点击操作；当用户勾选一项或者多项记录时，就把这个按钮的样式调整为正常样式，且响应点击操作。
如果只是上面的这样子的话，这类问题可以交给我们这边来做
@lsglsf

**Comment by sjx323** [comment]
codis界面如果未选中，是弹框提示选中一项，建议统一搞成弹框。

**Comment by lsglsf** [comment]
这里其实已经做了，只是有的按钮上面没有更新状态 @qqzxingchen
