### ISSUE TITLE
[全局]页面顶端的导航条和页面底端的footer占用了过多的空间

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#29]
如题，需要调整其占用的高度，以节省空间，显示更多的内容

**Comment by LuPan2015** [comment]
已调整并且已经配色. 具体调整后的界面如下:
![image](https://cloud.githubusercontent.com/assets/10804128/17992220/1143c7d6-6b78-11e6-904a-29c3cd93cb02.png)

**Comment by LuPan2015** [comment]
![image](https://cloud.githubusercontent.com/assets/10804128/17992236/37325e3a-6b78-11e6-87ca-6851c7c35051.png)
