### ISSUE TITLE
存储管理 - 回收站 - 进入回收站，一直显示加载中

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#31]
如下图。在切换到别的页面，再切换回来就不显示了
![qq20160816-0](https://cloud.githubusercontent.com/assets/13348433/17685164/22599ab4-6394-11e6-8bfd-4b1f84447e02.png)

**Comment by LuPan2015** [comment]
已复现： 文件分享 -> 回收站 即可复现

**Comment by LuPan2015** [comment]
已修复
