### ISSUE TITLE
存储管理-我的文件中，目录和文件的图标的颜色一样不易区分

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#33]
存储管理-我的文件中，目录和文件的图标的颜色一样不易区分。需要区分目录和文件的图标的颜色。

**Comment by LuPan2015** [comment]
![image](https://cloud.githubusercontent.com/assets/10804128/17888867/b1265c66-695f-11e6-88bc-aa783fb13da6.png)
 这样可以么？

**Comment by LuPan2015** [comment]
已按照上面方式解决。

**Comment by typhoonzero** [comment]
颜色都是同样的淡蓝色啊，显得页面很单调。
最左侧的图标的颜色， 文件名的文字， 右侧的分享下载等图标，使用不同颜色是否会更鲜明一点？

**Comment by typhoonzero** [comment]
@LuPan2015 可以和UI同事商量下配色。

**Comment by LuPan2015** [comment]
经和UI沟通，UI推荐的配色如下:
如果是文件则使用默认颜色，如果是目录则显示淡蓝色。图标只有有告警之类的才改变图标颜色。其余的推荐使用淡蓝色。
![image](https://cloud.githubusercontent.com/assets/10804128/17993286/191bd6ca-6b81-11e6-9322-a921994b4914.png)

**Comment by typhoonzero** [comment]
图展示的不对啊

**Comment by typhoonzero** [comment]
请在我LGTM之后再关闭这个issue

**Comment by LuPan2015** [comment]
![image](https://cloud.githubusercontent.com/assets/10804128/18046696/aa0c61ae-6e0b-11e6-8028-bcd296101447.png)
或者测试地址如下: http://172.24.3.64:10086

**Comment by typhoonzero** [comment]
右侧的图标没有变化？

**Comment by LuPan2015** [comment]
颜色变成了和字体是一样的颜色。和文件夹的颜色有点区分

**Comment by LuPan2015** [comment]
这个issue可以关闭么

**Comment by typhoonzero** [comment]
可以先关闭了，但是还有一个UE的问题：https://github.com/baifendian/Sirius/issues/89
