### ISSUE TITLE
[全局] 登录后，右上角没有选择space的时候也可以列出pod信息

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#34]
登录后，右上角没有选择space的时候也可以列出pod信息

这里可以有策略供讨论

1. 在没有获取到pod信息的时候，提示用户可以通过选择space查看
2. 当前页面需要根据space获取数据的时候，如果没有选择space，先优先提示用户选择space

**Comment by LuPan2015** [comment]
之前这里的策略是: 
     如果用户第一次登录我们会给他默认选择他属于的第一个space。
     如果用户为非第一次登录我们将默认给他选择他上次离开时所使用的space。

**Comment by sjx323** [comment]
每次切换space，默认space都会变化，直到最后一次切换，下次登录，默认选择上次space，应该不会出现空的情况

**Comment by sjx323** [comment]
还有一种情况 如果之前访问的space系统中没了，这种情况可能会报错。
