### ISSUE TITLE
经过多次操作后，鼠标会显示成手指型，而且不会还原成默认鼠标样式

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#35]
在界面上随意点击，操作几次之后，鼠标随机会变成手指型（放到链接上的鼠标样式），之后不论怎么操作，都不会再变回来。

**Comment by LuPan2015** [comment]
这个问题是发生在服务管理的页面吗？

**Comment by typhoonzero** [comment]
发现是在点击“我的任务”之后就会出现。 @hyndaniel

**Comment by LuPan2015** [comment]
那我分配给他。

**Comment by hyndaniel** [comment]
收到。

**Comment by hyndaniel** [comment]
已修复。
![image](https://cloud.githubusercontent.com/assets/18070336/18222887/0234c2a2-71d8-11e6-9435-ee04ab801b07.png)
