### ISSUE TITLE
k8s 页面样式

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#4]
### Datatable组件的选中行高亮功能需要自己实现
* UI开发人员通过讨论，建议选中行高亮功能由页面开发人员自己实现
* 涉及的页面包括：
    * /CalcManage/PodInfo
    * /CalcManage/ServiceInfo
    * /CalcManage/ReplicationControllerInfo

**Comment by Yancey1989** [comment]
这个功能是不是已经完成了？issue可以close了么？

**Comment by qqzxingchen** [comment]
已经完成了，但是还没有把代码合并到 dev 分支上，现在是在 gp-k8s-dashboard 分支上。等合并到dev分支上并简单测试没问题之后，就会把它关掉

**Comment by qqzxingchen** [comment]
已经实现，并提交到dev分支上了
