### ISSUE TITLE
计算管理 - 我的任务 的表格组件

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#46]
当刚打开这个页面并切换到表格组件子页面的时候，显示正常
但是如果此时点击表格的表头部分，如点击 “准备时间” ，则表头的布局会完全错位

**Comment by LuPan2015** [comment]
@qqzxingchen 最好加个截图呢？

**Comment by hyndaniel** [comment]
点击表头会变成这样
![image](https://cloud.githubusercontent.com/assets/18070336/17893643/070c347a-6979-11e6-97b0-690a19c5a4af.png)
