### ISSUE TITLE
制定完整的云中心导航栏

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#50]
现在的导航栏分为四个一级目录：
* 概览
* 存储管理
* 计算管理
* 用户管理

后续如果要整合更多的服务，这样的导航会有些难以找到对应功能。
初步设想：
* 首页
    * 开始使用
    * 文档
* 计算管理
    * k8s相关
    * openstack计算节点相关
    * 离线任务调度相关
    * storm调度相关
* 存储管理
    * HDFS
    * Ceph块存储(for docker and for openstack)
    * docker镜像
    * openstack镜像
    * 快照
* Codis云
* MySQL云
* ES云
* ......
* 用户管理

组织结构讨论下制定一个合理的版本

**Comment by Yancey1989** [comment]
我看到了https://github.com/baifendian/Sirius/issues/44中也提到了类似的问题，我说下我的想法：
按照按照以下这四个模块进行划分：
* 概览
* 存储管理
* 计算管理
* 用户管理

具体：
* 概览
* 存储
    * HDFS
    * Ceph
    * Codis
    * MySQL
    * ES
    * Docker Image
* 计算
    * k8s相关
    * openstack相关
    * batch job
    * storm 实时计算
* 用户管理
    * Space管理

**Comment by LuPan2015** [comment]
存储管理可以细分么？ 比如 关系型和非关系，结构化和非结构化？ 如果存储里面非的太粗的话后期会导致存储下面有很多一级子节点。

**Comment by linuxwind** [comment]
建议按计算，存储，网络，安全，数据库，大数据等等相关的划分大类。我稍微整理了一下，如下：

首页
＊ 开始
计算
＊ vm
＊ 容器
＊ 离线计算
＊ 在线计算
存储
* 对象存储(ceph rgw for s3, docker 镜像）
* 块存储 (openstack cinder with ceph rbd, docker volumes with ceph rbd)
* hdfs
* 备份(快照，克隆完整备份)
数据库
* mysql
* codis
* ...
网络
* vm 网络
* 容器网络
安全
＊ ..
大数据
＊ es
* ...
用户管理
* ...

**Comment by Yancey1989** [comment]
可将OpenStack相关的入口单独列出来，那么主要分为5个一级目录：

* 概览
* 用户管理
* 云服务
* 云容器
* 云主机

细分下来：
* 概览
* 用户管理
* 云服务
  * HDFS云
  * Codis云
* 云容器
  * k8s相关监控
  * Docker Image
  * 离线计算任务
  * storm实时计算任务
  * Ceph
* 云主机
  * VM网络
  * OpenStack Image
  * Openstack相关

**Comment by typhoonzero** [comment]
赞同 @Yancey1989 的思路，分开处理Openstack和k8s的一级模块。

**Comment by LuPan2015** [comment]
嗯。这样也行。

**Comment by linuxwind** [comment]
可以有，二级模块应该是根据具体情况设置吧？

**Comment by Yancey1989** [comment]
@linuxwind 是的，例如Openstack相关的按你给的原型就可以。

**Comment by Yancey1989** [comment]
这个修改要在哪个版本完成呢？@LuPan2015

**Comment by LuPan2015** [comment]
release-0.2中将把已经开发完成的功能按照 @Yancey1989  的方式调整。

**Comment by typhoonzero** [comment]
是可以确定下来了吧，一级目录的标题。

**Comment by LuPan2015** [comment]
我发现了个问题： 一级目录和二级目录下面其实也都要有概览页面。不然页面里面的面包屑在跳转的时候。不知道到跳转到一级目录或二级目录的那个页面去展示。

**Comment by LuPan2015** [comment]
此issue关闭了。
