### ISSUE TITLE
k8s 页面数据展示

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/Sirius#6]
### Pod、Service、RC的详情信息需要改变显示样式
* 涉及的页面包括：
    * /CalcManage/PodInfo
    * /CalcManage/ServiceInfo
    * /CalcManage/ReplicationControllerInfo

**Comment by typhoonzero** [comment]
是说控制台的内容么？

**Comment by qqzxingchen** [comment]
是详情信息，就是点击Pod列表的某项时，下面需要如何展示该Pod所有详情信息，当前的展示方法是：
PodConfig['status']['containerStatuses'][0]['restartCount'] = 0
PodConfig['status']['containerStatuses'][0]['name'] = codis-server6-1
......

**Comment by typhoonzero** [comment]
了解了，这个展示的时候需要可读一些，的确

**Comment by qqzxingchen** [comment]
已经更改，以 json 的格式显示，如：
![qq 20160812111811](https://cloud.githubusercontent.com/assets/8321444/17611957/8f09533e-607e-11e6-9e30-144a00974eef.png)
