### ISSUE TITLE
去掉源码中的二进制以及压缩包

### ISSUE THREAD

**Issue by Yancey1989** [baifendian/Sirius#65]
一般来说源码中不要包含压缩包和二进制文件，package目录下的压缩包和二进制文件需要去掉，这些都应该是上传至release中的。

**Comment by LuPan2015** [comment]
你指的是一下这4个包么？
![image](https://cloud.githubusercontent.com/assets/10804128/18152828/78506b20-702b-11e6-8b98-a7409caf7c84.png)

**Comment by Yancey1989** [comment]
@LuPan2015 是的

**Comment by LuPan2015** [comment]
@Yancey1989  里 kebectlxxxx的包是 [计算管理] 中镜像文件。客户端是可以通过页面下载的。所以这2个文件不能删除。 django-xxxx.tar.gz 这两个包可以删除。

**Comment by LuPan2015** [comment]
@Yancey1989  已经删除了 django-xxxx.tar.gz  这2个包。

**Comment by Yancey1989** [comment]
还有kubectl这两个二进制的文件，放在这里是做什么用的？

**Comment by abigbigbird** [comment]
codis有一些启动的二进制包也是必须的，不然没法启动，这个需要去掉么

**Comment by Yancey1989** [comment]
@LuPan2015 @abigbigbird 正确的做法这些二进制文件是上传至release下，在部署时通过部署脚本将这些文件下载回来。如果release-0.2来不及修改这些，可以在0.3来做。

**Comment by LuPan2015** [comment]
@Yancey1989  kubectl 的文件是 使用说明中的提供下载的文件。是服务依赖的文件。
