### ISSUE TITLE
[codis云] 点击某个codisid后页面出现unknown error

### ISSUE THREAD

**Issue by Yancey1989** [baifendian/Sirius#75]
如题，/v1/codis/getallcodisinfo/请求报405错误
<img width="1123" alt="qq20160901-0" src="https://cloud.githubusercontent.com/assets/1426912/18158295/04633e0c-7055-11e6-9b6a-14e0177de7ad.png">

**Comment by abigbigbird** [comment]
这个还在做，刚搭建好tsdb写进去 数据
