### ISSUE TITLE
用户管理-space列表偶会出现加载不出用户信息的情况

### ISSUE THREAD

**Issue by Yancey1989** [baifendian/Sirius#76]
<img width="1126" alt="qq20160901-1" src="https://cloud.githubusercontent.com/assets/1426912/18158396/a146dd82-7055-11e6-857f-443123d42e4c.png">

**Comment by LuPan2015** [comment]
跪求复现的方式。

**Comment by LuPan2015** [comment]
这个issue。我在下个版本中复现然后和ui那边联合解决。

**Comment by sjx323** [comment]
此问题已复现，正在修改
