### ISSUE TITLE
[codis云]添加host页面中hostip部分建议改为下拉框

### ISSUE THREAD

**Issue by Yancey1989** [baifendian/Sirius#77]
如题，手写IP会影响体验，并且容易写错。
<img width="779" alt="qq20160901-2" src="https://cloud.githubusercontent.com/assets/1426912/18158458/052ad948-7056-11e6-8c48-da1e54c96e02.png">

**Comment by abigbigbird** [comment]
这个新增加的时候在数据库里并没有，我们都不知道有哪些host信息，暂时没法搞成下拉框

**Comment by Yancey1989** [comment]
明白了，没有问题是我理解错了。
