### ISSUE TITLE
增加travis ci工具

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#78]
如题，增加travis ci工具完成自动编译和自动单元测试

**Comment by Yancey1989** [comment]
@hyndaniel travis ci工具是否已关联到这个repo？

**Comment by hyndaniel** [comment]
@typhoonzero @Yancey1989 前面跟江海讨论了一下关于单元测试的工具。他说想调研一下react的单元测试的工具，如果不着急的话，统一之后出个文档我们再去使用。现在前端编译这边已经没有问题。
