### ISSUE TITLE
概览 > 云服务 > HDFS云 > 配额管理 普通用户也可以修改配额？

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#88]
普通用户也可以修改配额

没注意到是否是管理员才能操作，还是yi.wu帐号已经加成管理员了？

**Comment by LuPan2015** [comment]
这确实是个权限上的bug. 在milestone0.3前修复

**Comment by LuPan2015** [comment]
权限控制是否可以这样:

1. 如果没有管理员权限是否可以直接不显示配额管理标签页。只显示配额监控标签页
2. 如果有管理员权限则按照现在的显示不变

**Comment by Yancey1989** [comment]
@LuPan2015 赞同陆攀的想法。

**Comment by LuPan2015** [comment]
已修复
