### ISSUE TITLE
概览 > 云服务 > HDFS云 > 我的文件 对文件，文件夹的删除等操作按钮样式

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#89]
对文件，文件夹的删除等操作按钮需要在鼠标移动之后高亮，并且在点击操作之后灰掉，参考github的按钮操作的情景

**Comment by LuPan2015** [comment]
目前页面的配色如下所示:
![image](https://cloud.githubusercontent.com/assets/10804128/18499234/87342dcc-7a6f-11e6-929e-2bc3eea6e14a.png)
主要修改部分为:

- 底部背景灰黑色
- 默认操作图标
- 获取焦点时图标背景深蓝色

**Comment by typhoonzero** [comment]
cool~

**Comment by LuPan2015** [comment]
调整了图标的大小:
![image](https://cloud.githubusercontent.com/assets/10804128/18662507/44779cb6-7f4d-11e6-80cd-c72d200a8a37.png)

**Comment by typhoonzero** [comment]
赞

**Comment by LuPan2015** [comment]
那我关闭了。
