### ISSUE TITLE
概览 > 云容器 > 离线计算任务 > 我的任务 搜索条件选择展示错位

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#92]
<img width="1054" alt="qq20160904-0 2x" src="https://cloud.githubusercontent.com/assets/13348433/18230202/d5df678a-72c6-11e6-99a9-6056068074f5.png">

**Comment by qqzxingchen** [comment]
了解，这个问题是屏幕适配问题，接下来会找个合适的方法解决它

**Comment by qqzxingchen** [comment]
问题已经解决，详看 #97
