### ISSUE TITLE
当前页面对应左侧导航菜单没有高亮，或高亮的菜单没有对应到页面

### ISSUE THREAD

**Issue by typhoonzero** [baifendian/Sirius#94]
<img width="482" alt="qq20160904-1 2x" src="https://cloud.githubusercontent.com/assets/13348433/18230228/88697a1c-72c7-11e6-997c-24b97fe507ab.png">

**Comment by LuPan2015** [comment]
这是展开的不对是吧。应该是展开使用说明。高亮 开始使用 吧. [关联百分点ui issue]: http://git.baifendian.com/front-end/bfd-ui/issues/131

**Comment by hyndaniel** [comment]
收到

**Comment by LuPan2015** [comment]
@hyndaniel  你跟踪一下百分点ui 那边的修复进度。

**Comment by hyndaniel** [comment]
@LuPan2015 好的。

**Comment by hyndaniel** [comment]
导航栏的 **高亮问题**、**无法收回二级目录的问题** 已经解决。是我们的编码问题。。。  
接下来**切换一级菜单，收回其他一级菜单**的问题是需要bfd-ui支持的。  
已经提了comment @LuPan2015

**Comment by typhoonzero** [comment]
需要关联多级菜单都高亮。先打开了。

**Comment by hyndaniel** [comment]
像云容器底下的菜单那样吗？ @typhoonzero

**Comment by typhoonzero** [comment]
云容器下菜单也只到2级目录，应该是点击路径的每一级都高亮。看来是需要升级端库了，升级之后再关闭此issue吧

**Comment by hyndaniel** [comment]
云容器下的菜单是每级都高亮的，只不过第三级颜色很淡，得仔细看。。。
